name: build

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true

jobs:
  build:
    strategy:
      matrix:
        os:
          - { image: ubuntu-22.04, name: linux }
          - { image: ubuntu-20.04, name: linux }
    runs-on: ${{ matrix.os.image }}
    env:
      CI_OS_NAME: ${{ matrix.os.name }}
      CI_RUNS_ON: ${{ matrix.os.image }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: 'verilator/verilator'
        ref: ${{ github.event.inputs.version }}
    - name: Install packages for build
      run: ./ci/ci-install.bash
    - name: Build
      run: ./ci/ci-script.bash
