name: build

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    strategy:
      matrix:
        os:
          - { image: ubuntu-22.04, name: linux }
          - { image: ubuntu-20.04, name: linux }
    runs-on: ${{ matrix.os.image }}
    env:
      CI_BUILD_STAGE_NAME: build
      CI_OS_NAME: ${{ matrix.os.name }}
      CI_RUNS_ON: ${{ matrix.os.image }}
    permissions:
      contents: write
    steps:
    - name: Setup variables
       id: variables
       run: echo "::set-output name=tag::${GITHUB_REF##*/}"
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: 'verilator/verilator'
        ref: ${{ steps.variables.outputs.tag }}
    - name: Install packages for build
      run: ./ci/ci-install.bash
    - name: Build
      run: ./ci/ci-script.bash
    - name: Package
      run: |
        mkdir dist
        cp LICENSE dist
        cp README.rst dist
        cp -r bin dist
        cp -r include dist
        cp *.cmake dist
        rm dist/bin/verilator_bin_dbg
        pushd dist
        zip -r ../verilator-${{ matrix.os.image }}.zip .
        popd
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: "*.zip"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
